name: CI
on: [push, pull_request]
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2- name:SetupNode.js
    uses:actions/setup-node@v2with:
    node-version: '14'
- name:  Install  dependencies
  run: npm install
   - name: Run tests
  run: npm tes
